name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
          name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIAL }}
      -
          name: Check out repository code
          uses: actions/checkout@v3
      -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: BiliCLOnline/Dockerfile
            push: true
            tags: injectrl/biliclonline:latest
      -
          name: Deploy to ACI
          uses: Azure/aci-deploy@v1
          with:
            resource-group: biliclonline
            image: injectrl/biliclonline:latest
            name: biliclonline
            location: 'Korea Central'
